name: Lint & Typecheck

on:
  workflow_call:

jobs:
  lint-check:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup JS environment
        uses: ./.github/actions/setup-js

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run check

      - name: Build
        run: bun run build

      - name: Lint Generated HTML
        run: bun run lint:html

      - name: Lint GitHub Actions
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/393031adb9afb225ee52ae2ccd7a5af5525e03e8/scripts/download-actionlint.bash) 1.7.11 # v1.7.11
          ./actionlint -color
        shell: bash
